source 'https://rubygems.org'

require 'json'
require 'open-uri'
versions = JSON.parse(open('./versions.json').read)

gem 'github-pages', '>= 214', versions['github-pages']

gem 'html-proofer', '>= 3.10.0'
